name: Submit
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update:
    name: EAS Submit
    runs-on: ubuntu-latest
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Setup EAS
        uses: ./.github/actions/eas

      - name: Publish update
        run: eas update --branch ${{ github.ref_name }} --auto
